name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: GoogleCloudPlatform/magic-modules
          upstream_sync_branch: main
          target_sync_branch: main
          # USE THE NEW SECRET HERE INSTEAD OF GITHUB_TOKEN
          target_repo_token: ${{ secrets.REPO_SYNC }}

          test_mode: false

      - name: Timestamp
        run: date
